// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: video/server.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	detail "tinytiktok/video/proto/detail"
	favorite "tinytiktok/video/proto/favorite"
	feed "tinytiktok/video/proto/feed"
	like "tinytiktok/video/proto/like"
	publish "tinytiktok/video/proto/publish"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VideoService_Feed_FullMethodName         = "/userServer.VideoService/Feed"
	VideoService_Like_FullMethodName         = "/userServer.VideoService/Like"
	VideoService_FavoriteList_FullMethodName = "/userServer.VideoService/FavoriteList"
	VideoService_Publish_FullMethodName      = "/userServer.VideoService/Publish"
	VideoService_PublishList_FullMethodName  = "/userServer.VideoService/PublishList"
	VideoService_Detail_FullMethodName       = "/userServer.VideoService/Detail"
)

// VideoServiceClient is the client API for VideoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoServiceClient interface {
	// 返回最近30条视频信息[最多]
	Feed(ctx context.Context, in *feed.FeedRequest, opts ...grpc.CallOption) (*feed.FeedResponse, error)
	// 用户点赞实现
	Like(ctx context.Context, in *like.LikeRequest, opts ...grpc.CallOption) (*like.LikeResponse, error)
	// 返回用户喜欢的视频列表
	FavoriteList(ctx context.Context, in *favorite.FavoriteListRequest, opts ...grpc.CallOption) (*favorite.FavoriteListResponse, error)
	// 用户发布视频实现
	Publish(ctx context.Context, in *publish.PublishRequest, opts ...grpc.CallOption) (*publish.PublishResponse, error)
	// 发布列表
	PublishList(ctx context.Context, in *publish.PublishListRequest, opts ...grpc.CallOption) (*publish.PublishListResponse, error)
	// 用户的视频详细信息
	Detail(ctx context.Context, in *detail.DetailRequest, opts ...grpc.CallOption) (*detail.DetailResponse, error)
}

type videoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoServiceClient(cc grpc.ClientConnInterface) VideoServiceClient {
	return &videoServiceClient{cc}
}

func (c *videoServiceClient) Feed(ctx context.Context, in *feed.FeedRequest, opts ...grpc.CallOption) (*feed.FeedResponse, error) {
	out := new(feed.FeedResponse)
	err := c.cc.Invoke(ctx, VideoService_Feed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) Like(ctx context.Context, in *like.LikeRequest, opts ...grpc.CallOption) (*like.LikeResponse, error) {
	out := new(like.LikeResponse)
	err := c.cc.Invoke(ctx, VideoService_Like_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) FavoriteList(ctx context.Context, in *favorite.FavoriteListRequest, opts ...grpc.CallOption) (*favorite.FavoriteListResponse, error) {
	out := new(favorite.FavoriteListResponse)
	err := c.cc.Invoke(ctx, VideoService_FavoriteList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) Publish(ctx context.Context, in *publish.PublishRequest, opts ...grpc.CallOption) (*publish.PublishResponse, error) {
	out := new(publish.PublishResponse)
	err := c.cc.Invoke(ctx, VideoService_Publish_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) PublishList(ctx context.Context, in *publish.PublishListRequest, opts ...grpc.CallOption) (*publish.PublishListResponse, error) {
	out := new(publish.PublishListResponse)
	err := c.cc.Invoke(ctx, VideoService_PublishList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) Detail(ctx context.Context, in *detail.DetailRequest, opts ...grpc.CallOption) (*detail.DetailResponse, error) {
	out := new(detail.DetailResponse)
	err := c.cc.Invoke(ctx, VideoService_Detail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServiceServer is the server API for VideoService service.
// All implementations must embed UnimplementedVideoServiceServer
// for forward compatibility
type VideoServiceServer interface {
	// 返回最近30条视频信息[最多]
	Feed(context.Context, *feed.FeedRequest) (*feed.FeedResponse, error)
	// 用户点赞实现
	Like(context.Context, *like.LikeRequest) (*like.LikeResponse, error)
	// 返回用户喜欢的视频列表
	FavoriteList(context.Context, *favorite.FavoriteListRequest) (*favorite.FavoriteListResponse, error)
	// 用户发布视频实现
	Publish(context.Context, *publish.PublishRequest) (*publish.PublishResponse, error)
	// 发布列表
	PublishList(context.Context, *publish.PublishListRequest) (*publish.PublishListResponse, error)
	// 用户的视频详细信息
	Detail(context.Context, *detail.DetailRequest) (*detail.DetailResponse, error)
	mustEmbedUnimplementedVideoServiceServer()
}

// UnimplementedVideoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVideoServiceServer struct {
}

func (UnimplementedVideoServiceServer) Feed(context.Context, *feed.FeedRequest) (*feed.FeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Feed not implemented")
}
func (UnimplementedVideoServiceServer) Like(context.Context, *like.LikeRequest) (*like.LikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Like not implemented")
}
func (UnimplementedVideoServiceServer) FavoriteList(context.Context, *favorite.FavoriteListRequest) (*favorite.FavoriteListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FavoriteList not implemented")
}
func (UnimplementedVideoServiceServer) Publish(context.Context, *publish.PublishRequest) (*publish.PublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedVideoServiceServer) PublishList(context.Context, *publish.PublishListRequest) (*publish.PublishListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishList not implemented")
}
func (UnimplementedVideoServiceServer) Detail(context.Context, *detail.DetailRequest) (*detail.DetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detail not implemented")
}
func (UnimplementedVideoServiceServer) mustEmbedUnimplementedVideoServiceServer() {}

// UnsafeVideoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServiceServer will
// result in compilation errors.
type UnsafeVideoServiceServer interface {
	mustEmbedUnimplementedVideoServiceServer()
}

func RegisterVideoServiceServer(s grpc.ServiceRegistrar, srv VideoServiceServer) {
	s.RegisterService(&VideoService_ServiceDesc, srv)
}

func _VideoService_Feed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(feed.FeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).Feed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_Feed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).Feed(ctx, req.(*feed.FeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_Like_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(like.LikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).Like(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_Like_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).Like(ctx, req.(*like.LikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_FavoriteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(favorite.FavoriteListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).FavoriteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_FavoriteList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).FavoriteList(ctx, req.(*favorite.FavoriteListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(publish.PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).Publish(ctx, req.(*publish.PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_PublishList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(publish.PublishListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).PublishList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_PublishList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).PublishList(ctx, req.(*publish.PublishListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_Detail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(detail.DetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).Detail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_Detail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).Detail(ctx, req.(*detail.DetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoService_ServiceDesc is the grpc.ServiceDesc for VideoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userServer.VideoService",
	HandlerType: (*VideoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Feed",
			Handler:    _VideoService_Feed_Handler,
		},
		{
			MethodName: "Like",
			Handler:    _VideoService_Like_Handler,
		},
		{
			MethodName: "FavoriteList",
			Handler:    _VideoService_FavoriteList_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _VideoService_Publish_Handler,
		},
		{
			MethodName: "PublishList",
			Handler:    _VideoService_PublishList_Handler,
		},
		{
			MethodName: "Detail",
			Handler:    _VideoService_Detail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "video/server.proto",
}
